version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: ChatApp
    ports:
      - "27017:27017"
    volumes:
      - my_mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  my_mongodb_data:
